#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Atualizar CHANGELOG
npx conventional-changelog -p conventionalcommits -i CHANGELOG.md -s -r 0
git add CHANGELOG.md
HUSKY=0 git commit --amend --no-edit || true
