#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Garante que a execução seja a partir do diretório raiz
cd "$(git rev-parse --show-toplevel)"

# Gera/atualiza o CHANGELOG.md com base nos commits existentes
npx conventional-changelog -p conventionalcommits -i CHANGELOG.md -s

# Verifica se houve alterações no CHANGELOG.md
if ! git diff --quiet CHANGELOG.md; then
  git add CHANGELOG.md
  git commit -m "chore: atualiza changelog [ci skip]" || true
fi
